// src-old/components/ui/card.tsx
import { cn } from "@/lib/utils";
import React from "react";

const Card = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn("rounded-lg border bg-card p-4 shadow", className)}
    {...props}
  />
));
Card.displayName = "Card";

export { Card };

// src/lib/components/ui/card/card.svelte
<script lang="ts">
  import type { HTMLAttributes } from "svelte/elements";
  import { cn, type WithElementRef } from "$lib/utils.js";

  let {
    ref = $bindable(null),
    class: className,
    children,
    ...restProps
  }: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
  bind:this={ref}
  data-slot="card"
  class={cn("bg-card rounded-lg border p-4 shadow", className)}
  {...restProps}
>
  {@render children?.()}
</div>
